apiVersion: cloudshell.cloudtty.io/v1alpha1
kind: CloudShell
metadata:
  name: cloudshell-sample
spec:
  secretRef:
    name: "my-kubeconfig"
  runAsUser: "root"
  commandAction: "bash"
  ttl: 500
  once: false
  image: ghcr.io/cloudtty/cloudshell:v0.5.0
