apiVersion: cloudshell.cloudtty.io/v1alpha1
kind: CloudShell
metadata:
  name: nginx-demo
  namespace: "cloudtty-system"
spec:
 configmapName: "my-kubeconfig"
 runAsUser: "root"
 commandAction: "bash"
 exposureMode: "Ingress"
 pathPrefix: "/apis/cloudtty.io/"
 ttl: 500
 once: false
 ingressConfig: 
   ingressName: "cloudshell-ingress-demo"
   namespace: "cloudtty-system"
   ingressClassName: "nginx"
